from brb import BrbMatcher
from greeter import GreetingMatcher
from sifter import SifterMatcher
from googleplus import ArthurGooglePlusMatcher
from gifter import GifterMatcher
from sandwich import SandwichMatcher
from cletus import CletusMatcher
from jenkins import JenkinsMatcher
from volunteer import VolunteerMatcher
from lunch import LunchMatcher
from timezones import TimezoneMatcher
from points import PointsMatcher
from silly import SillyMatcher
